# Daily Retrospective

**작성자**: [황주원]  
**작성일시**: [2025-02-25]

## 1. 오늘 배운 내용 (필수)
### slip validator exception 반환 흐름

XXXExecuteSetupMainProgram.ts 에서 validator 를 실행시키고, 오류를 throw 하고 있습니다.

```ts
const slip_validator_result = slip_validator_program.execute({
    dmc: this.dmc,
    slip_data_model: slip,
    slip_attributes: this.smc.getAttrsByAttrType(EN_ATTR_TYPE.Validator),
    additional_info: request.additional_info,
});

if (!_.vIsEmpty(slip_validator_result.exceptions)) {
    Exception.throw(
        ExceptionBuilder.create<IValidateSlipDataModelException>(IValidateSlipDataModelException, {
            exceptions: slip_validator_result.exceptions,
        })
    );
}
```

여기서 끝일거라고 생각했지만, 브라우저단에서 해당 오류를 보고 화면에 뿌립니다.

XXXUserAction에서 브라우저단 XXXExecuteSetupMainProgram을 호출하고, 에러 확인 처리 작업을 진행합니다.

해당 API 호출하면서 에러를 가져오고 담아서 UserAction으로 리턴해주고 있습니다.
```ts
    ... 앞단 로직 ...

    //API 호출
    this.api_request = this.getActionRequest(this.execution_context, dto);
    api_result = await api_resolver_program.executeAsync({
        attributes: this.menu_definition.attributes?.filter((x) => x.attr_type == EN_ATTR_TYPE.Api),
        action_request: this.api_request,
    });

    if (_.vIsEmpty(api_result.result.error) == false) {
        errors.push(api_result.result.error ?? ({} as IException));
    }
    //this.result.data_model = api_result.result.data_model;
    //	this.result = api_result.result;
    this.result.data_model = api_result.result.data_model;
    this.result.additional_info = api_result;
    this.result.slip_created_result = api_result.result.slip_created_result;
    } catch (e) {
    const ex = Exception.verifyOrThrow(e);
    errors.push(ex ?? ({} as IException));
    } finally {
        if (!_.vIsEmpty(errors)) {
            this.result.error = ExceptionBuilder.create<ICommonException>(ICommonException, {
                error_info: errors,
            });
        }

    }

    ... 뒷단 validator resolver 실행 로직 ...
```

UserAction에서 ExecuteSetup 프로그램에서 전달받은 오류들을 Exection Builder 로 create 하게 되는데, 이건 서버쪽에서 에러 처리로직과 동일합니다.

```ts
const result = await program.executeAsync({
    dm_manager,
    vmc: vmc,
    // current_template,
});

if (result.error) {
    handleError(execution_context, result.error);
}

function handleError(execution_context: IExecutionContext, error: any): never {
	execution_context.action.action_mode =
		execution_context.action.action_mode === EN_ACTION_MODE.Create
			? EN_ACTION_MODE.GetCreate
			: EN_ACTION_MODE.GetModify;
	throw ExceptionBuilder.create(error.name, error);
}
```


## 2. 동기에게 도움 받은 내용 (필수)
* 도형님께서 UserAction에서 타는 에러 처리 방법에 대해 설명해주셨습니다. 감사합니다!
* 수경님과 버전체크 오류에 대해 함께 고민했습니다. 감사합니다!
* 수경님, 강민님과 잠깐 바람을 쐬며 답답함을 풀 수 있었습니다. 감사합니다!

---

## 3. 개발 기술적으로 성장한 점 (선택)

### 1. 교육 과정 상 배운 내용이 아닌 개인적 호기심을 해결하기 위해 추가 공부한 내용

### 2. 오늘 직면했던 문제 (개발 환경, 구현)와 해결 방법
#### 2-1. 삭제가 되지 않은 이슈
삭제 시 에러가 발생하고 있다는 문의가 있었습니다.

확인해 보니 버전체크로직에서 오류가 발생했으며, 해당 줄에서 getFeature를 하면 발생했습니다.

```ts
const check_version_feature = this.execution_context.getFeature<IVersionCheckFeature>(IVersionCheckFeature);
```

Feature를 등록(set)해준 곳이 없어 발생한 에러였습니다. 아래 코드를 적용해야 할 action에 추가해주니 삭제가 정상적으로 작동하였습니다.

```ts
configuration_context.setFeature<IVersionCheckFeature>(
    IVersionCheckFeature,
    new BizzVersionCheckFeature(execution_context)
);
```

#### 2-2. 버전체크가 삭제에서 동작하지 않은 이슈
버전체크가 `수정`에서는 동작하지만, `삭제`에서는 동작하지 않는 이슈가 있었습니다.

서버단 ExecuteSetupMainProgram에서 

![이슈2](../ref/황주원%20이미지/이슈2.png)

1번 오늘 배운 내용과 같이 validator exception 반환 흐름을 파악해보며 원인이 브라우저단에 있다는 것을 알게 되었습니다.


### 3. 위 두 주제 중 미처 해결 못한 과제. 앞으로 공부해볼 내용.
버전 체크가 현재 버전으로 동작되지 않는 것이 맞다. <br />
생각한 방안으로는, <br />
✔️ 브라우저단 ExecuteSetupMainProgram을 수정해서 새로운 ExecuteSetupProgram을 만들기 <br />
✔️ 알럿창을 띄우기 <br />
✔️ 삭제에 대한 버전체크 넘어가기 <br />

---

## 4. 소프트 스킬면에서 성장한 점 
팀장님께서 다시 한 번 회고록의 중요성을 알려주셔서 감사했습니다. 프로젝트하면서 신경쓰지 못 했던 부분들에 대해 반성할 수 있었습니다. 